### PR TITLE
Implement download function with tempfile

### PR DESCRIPTION
**Pull request by ThomDietrich**
Hey @yann25,

The script worked great on initial tests. I've implemented the tempfile download as we discussed in #3 and added some verbosity and error checking.

FYI I've tested the download but not the whole process...

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Did you get around to test it?

**Comment by yann25** [comment]
Yes unfortunately it did not work is there a way to go back? I will look at it this evenig. I looked at the code and it looked good :D

**Comment by yann25** [comment]
I must say I have starting problems using the git flow. I think I reverted it, but still have it local to test it... 🙈

**Comment by ThomDietrich** [comment]
The function should work. There could be an issue accessing the downloaded file for flashing. I did not test a real device flash after everything was finished.

**Comment by yann25** [comment]
I just looked at the code. This is basiclly the same way I used the tempfile:

https://gist.github.com/yann25/80d4ffba1e83f4936ea1b182898f4d17

So I re-ran my tempfile testfile and searched fpr the tempfile as soon as data was written into it. It said 0 KB. I tried it several times with the same result, but when I tested it in the beginning I had a 460 KB tempfile. 

As soon as esptools is writing the bin file, that has 0KB it crashes. Then the whole script stops without giving out an error.

**Comment by ThomDietrich** [comment]
I've recreated the PR. I'm pretty confident it does what it should.

Regarding git: That's pretty normal. No worries, you'll get a hold of it quickly.

**Pull request merged**
